name: pangeo
channels:
  - defaults
  - conda-forge
dependencies:
  - timezonefinder
  - xgcm
  - h5py
  - param
  - python-lsp-ruff
  - argopy[version='<0.1.16']
  - sparse
  - jupyterlab-lsp
  - pystac-client
  - python-gist
  - intake-xarray
  - xhistogram
  - bottleneck
  - xgboost
  - line_profiler
  - fastjmd95
  - pydap
  - ciso
  - h5netcdf
  - ipyleaflet
  - stackstac
  - scikit-image
  - seaborn
  - black
  - gh
  - hvplot
  - pyarrow
  - xarray
  - ipytree
  - rio-cogeo
  - snakeviz
  - cmocean
  - geocube
  - jupyterlab-myst
  - xxhash
  - rioxarray
  - awscli
  - gcm_filters
  - pystac
  - xrft
  - holoviews
  - cdsapi
  - gh-scoped-creds
  - zarr==2.16.1
  - ruff
  - matplotlib-base
  - duckdb-cli
  - jupyterlab-git
  - flox
  - esmpy
  - dask-geopandas
  - intake-geopandas
  - cartopy
  - ipdb
  - boto3
  - adlfs
  - kerchunk
  - numpy
  - pop-tools
  - xskillscore
  - xmitgcm
  - jupyterlab_code_formatter
  - satpy
  - lonboard
  - nb_conda_kernels
  - geopandas
  - cfgrib
  - python-xxhash
  - xarray_leaflet
  - gdal
  - rasterio
  - xmip
  - ipykernel
  - jupyter-sshd-proxy
  - numpy_groupies
  - cf_xarray
  - earthaccess[version='<0.13.0']
  - watermark
  - scipy
  - xesmf
  - memory_profiler
  - netcdf4
  - numbagg
  - lz4
  - gcsfs
  - python-graphviz
  - xpublish
  - scikit-learn
  - nc-time-axis
  - rechunker
  - odc-stac
  - python-blosc
  - lxml
  - s3fs
  - contextily
  - metpy
  - intake
  - geoviews-core
  - xarray-spatial
  - ipympl
  - gsw
  - openssh
  - fsspec
  - ipywidgets
  - nbstripout
  - eofs
  - xarrayutils
  - intake-esm[version='<2025.2.3']
  - xvec
  - jupyter-resource-usage
  - dask-ml
  - intake-stac
  - jupyter-panel-proxy
  - xclim
  - descartes
  - git-lfs
  - numcodecs
  - erddapy
  - xbatcher
  - geopy
  - python-duckdb
  - pandas
  - datashader
  - tiledb-py
  - planetary-computer
  - panel
  - pycamhd
  - dask=2025.2.0
  - xcube
  - jupyterlab
  - pip:
    - tabulate
    - xpystac
    - xrlint
    - dask_labextension
